init:
  - git config --global core.autocrlf true

image: Visual Studio 2017

build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "Pack" -Verbosity Diagnostic

test: on